<a href="https://colab.research.google.com/github/aksho0/Python-Practice/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pandas is an open-source library which is used for handle data manipulation

In [1]:
import pandas as pd

In [ ]:
# Data Structures of Pandas -->
# 1. Series : it's a 1D data structure that stores only values not cloumn name
# 2. Dataframe : it's a multudimensional data structure that stores data along with thier coloumn names

In [ ]:
#----Series-----
a = pd.Series([1, 45, 78, 90])
a

0     1
1    45
2    78
3    90
dtype: int64

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
#----DataFrame--------
a = {
    "emp_id" : [1,2,3,4,5],
    "name" : ["Sam", "Mohit", "Raj", "Rahul", "Aniket"],
    "Dept" : ["IT", "Sales", "IT", "IT", "Sales"],
    "salary" : [20000, 25000, 30000, 31000, 26000]
}

In [ ]:
df = pd.DataFrame(a)
a

{'emp_id': [1, 2, 3, 4, 5],
 'name': ['Sam', 'Mohit', 'Raj', 'Rahul', 'Aniket'],
 'Dept': ['IT', 'Sales', 'IT', 'IT', 'Sales'],
 'salary': [20000, 25000, 30000, 31000, 26000]}

In [3]:
# student_id, name, course, course duration, total fees
# export this df into csv and excel
# and you have to create a new repo student data and upload it to git hub

info = {
    "stud_id" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name" :  ['Sam', 'Mohit', 'Raj', 'Rahul', 'Aniket', 'Rohan', 'Payal', 'Poonam', 'Samarth', 'Anu'],
    "course" : ['Btech', 'BCA', 'BVA', 'BCA', 'Btech', 'BCom', 'BSc', 'MCA', 'MBA', 'BBA'],
    "course_dur" : [4, 3, 4, 3, 4, 3, 3, 2, 2, 4],
    "fees" : [400000, 300000, 400000, 300000, 400000, 300000, 300000, 200000, 200000, 400000]
}

stud_info = pd.DataFrame(info)
stud_info

   stud_id     name course  course_dur    fees
0        1      Sam  Btech           4  400000
1        2    Mohit    BCA           3  300000
2        3      Raj    BVA           4  400000
3        4    Rahul    BCA           3  300000
4        5   Aniket  Btech           4  400000
5        6    Rohan   BCom           3  300000
6        7    Payal    BSc           3  300000
7        8   Poonam    MCA           2  200000
8        9  Samarth    MBA           2  200000
9       10      Anu    BBA           4  400000

In [4]:
stud_info.to_csv("stud_info.csv")

In [6]:
stud_info.to_excel("stud_info.xlsx")